package SUSHI::SUSHITypes::CustomerReference;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.niso.org/schemas/sushi' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ID_of :ATTR(:get<ID>);
my %Name_of :ATTR(:get<Name>);

__PACKAGE__->_factory(
    [ qw(       
        ID
        Name
    ) ],
    {
        'ID' => \%ID_of,
        'Name' => \%Name_of,
    },
    {
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ID' => 'ID',
        'Name' => 'Name',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

SUSHI::SUSHITypes::CustomerReference

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CustomerReference from the namespace http://www.niso.org/schemas/sushi.

A reference to a customer for which data is requested.




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ID


=item * Name




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::CustomerReference
   ID =>  $some_value, # string
   Name =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

