package SUSHI::SUSHITypes::Customer;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://www.niso.org/schemas/counter' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(SUSHI::SUSHITypes::Organization);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Name_of :ATTR(:get<Name>);
my %ID_of :ATTR(:get<ID>);
my %Contact_of :ATTR(:get<Contact>);
my %WebSiteUrl_of :ATTR(:get<WebSiteUrl>);
my %LogoUrl_of :ATTR(:get<LogoUrl>);
my %Consortium_of :ATTR(:get<Consortium>);
my %InstitutionalIdentifier_of :ATTR(:get<InstitutionalIdentifier>);

__PACKAGE__->_factory(
    [ qw(        Name
        ID
        Contact
        WebSiteUrl
        LogoUrl
        Consortium
        InstitutionalIdentifier

    ) ],
    {
        'Name' => \%Name_of,
        'ID' => \%ID_of,
        'Contact' => \%Contact_of,
        'WebSiteUrl' => \%WebSiteUrl_of,
        'LogoUrl' => \%LogoUrl_of,
        'Consortium' => \%Consortium_of,
        'InstitutionalIdentifier' => \%InstitutionalIdentifier_of,
    },
    {
        'Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Contact' => 'SUSHI::SUSHITypes::Contact',
        'WebSiteUrl' => 'SOAP::WSDL::XSD::Typelib::Builtin::anyURI',
        'LogoUrl' => 'SOAP::WSDL::XSD::Typelib::Builtin::anyURI',
        'Consortium' => 'SUSHI::SUSHITypes::Consortium',
        'InstitutionalIdentifier' => 'SUSHI::SUSHITypes::Identifier',
    },
    {

        'Name' => 'Name',
        'ID' => 'ID',
        'Contact' => 'Contact',
        'WebSiteUrl' => 'WebSiteUrl',
        'LogoUrl' => 'LogoUrl',
        'Consortium' => 'Consortium',
        'InstitutionalIdentifier' => 'InstitutionalIdentifier',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

SUSHI::SUSHITypes::Customer

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Customer from the namespace http://www.niso.org/schemas/counter.

Details about the customer whose data the report represents.




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Consortium


=item * InstitutionalIdentifier




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::Customer
   Consortium =>  { # SUSHI::SUSHITypes::Consortium
     Code =>  $some_value, # string
     WellKnownName =>  $some_value, # string
   },
   InstitutionalIdentifier =>  { # SUSHI::SUSHITypes::Identifier
     Type => $some_value, # IdentifierType
     Value =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

