package SUSHI::SUSHITypes::DateRange;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://www.niso.org/schemas/counter' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Begin_of :ATTR(:get<Begin>);
my %End_of :ATTR(:get<End>);

__PACKAGE__->_factory(
    [ qw(        Begin
        End

    ) ],
    {
        'Begin' => \%Begin_of,
        'End' => \%End_of,
    },
    {
        'Begin' => 'SOAP::WSDL::XSD::Typelib::Builtin::date',
        'End' => 'SOAP::WSDL::XSD::Typelib::Builtin::date',
    },
    {

        'Begin' => 'Begin',
        'End' => 'End',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

SUSHI::SUSHITypes::DateRange

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
DateRange from the namespace http://www.niso.org/schemas/counter.

The time period (representing a month) for the the usage.




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Begin


=item * End




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::DateRange
   Begin =>  $some_value, # date
   End =>  $some_value, # date
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

