package SUSHI::SUSHITypes::Exception;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://www.niso.org/schemas/sushi' };

our $XML_ATTRIBUTE_CLASS = 'SUSHI::SUSHITypes::Exception::_Exception::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Number_of :ATTR(:get<Number>);
my %Severity_of :ATTR(:get<Severity>);
my %Message_of :ATTR(:get<Message>);
my %HelpUrl_of :ATTR(:get<HelpUrl>);
my %Data_of :ATTR(:get<Data>);

__PACKAGE__->_factory(
    [ qw(        Number
        Severity
        Message
        HelpUrl
        Data

    ) ],
    {
        'Number' => \%Number_of,
        'Severity' => \%Severity_of,
        'Message' => \%Message_of,
        'HelpUrl' => \%HelpUrl_of,
        'Data' => \%Data_of,
    },
    {
        'Number' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'Severity' => 'SUSHI::SUSHITypes::ExceptionSeverity',
        'Message' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'HelpUrl' => 'SOAP::WSDL::XSD::Typelib::Builtin::anyURI',
        'Data' => 'SOAP::WSDL::XSD::Typelib::Builtin::anyType',
    },
    {

        'Number' => 'Number',
        'Severity' => 'Severity',
        'Message' => 'Message',
        'HelpUrl' => 'HelpUrl',
        'Data' => 'Data',
    }
);

} # end BLOCK




package SUSHI::SUSHITypes::Exception::_Exception::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %Created_of :ATTR(:get<Created>);

__PACKAGE__->_factory(
    [ qw(
        Created
    ) ],
    {

        Created => \%Created_of,
    },
    {
        Created => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

SUSHI::SUSHITypes::Exception

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Exception from the namespace http://www.niso.org/schemas/sushi.

Service Exceptions




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Number


=item * Severity


=item * Message


=item * HelpUrl


=item * Data




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::Exception
   Number =>  $some_value, # int
   Severity => $some_value, # ExceptionSeverity
   Message =>  $some_value, # string
   HelpUrl =>  $some_value, # anyURI
   Data =>  $some_value, # anyType
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class SUSHI::SUSHITypes::Exception::_Exception::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * Created



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::dateTime|SOAP::WSDL::XSD::Typelib::Builtin::dateTime>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

