package SUSHI::SUSHITypes::Metric;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://www.niso.org/schemas/counter' };

our $XML_ATTRIBUTE_CLASS = 'SUSHI::SUSHITypes::Metric::_Metric::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Period_of :ATTR(:get<Period>);
my %Category_of :ATTR(:get<Category>);
my %Instance_of :ATTR(:get<Instance>);

__PACKAGE__->_factory(
    [ qw(        Period
        Category
        Instance

    ) ],
    {
        'Period' => \%Period_of,
        'Category' => \%Category_of,
        'Instance' => \%Instance_of,
    },
    {
        'Period' => 'SUSHI::SUSHITypes::DateRange',
        'Category' => 'SUSHI::SUSHITypes::Category',
        'Instance' => 'SUSHI::SUSHITypes::PerformanceCounter',
    },
    {

        'Period' => 'Period',
        'Category' => 'Category',
        'Instance' => 'Instance',
    }
);

} # end BLOCK




package SUSHI::SUSHITypes::Metric::_Metric::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %PubYr_of :ATTR(:get<PubYr>);

__PACKAGE__->_factory(
    [ qw(
        PubYr
    ) ],
    {

        PubYr => \%PubYr_of,
    },
    {
        PubYr => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

SUSHI::SUSHITypes::Metric

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Metric from the namespace http://www.niso.org/schemas/counter.

The actual usage details.




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Period


=item * Category


=item * Instance




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::Metric
   Period =>  { # SUSHI::SUSHITypes::DateRange
     Begin =>  $some_value, # date
     End =>  $some_value, # date
   },
   Category => $some_value, # Category
   Instance =>  { # SUSHI::SUSHITypes::PerformanceCounter
     MetricType => $some_value, # MetricType
     Count =>  $some_value, # nonNegativeInteger
   },
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class SUSHI::SUSHITypes::Metric::_Metric::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * PubYr

 Year of publication. (This is currently ONLY used by Journal Report 5 which requires a breakdown of usage by year published; therefore, omit for all other reports)



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::int|SOAP::WSDL::XSD::Typelib::Builtin::int>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

