package SUSHI::SUSHITypes::PerformanceCounter;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://www.niso.org/schemas/counter' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %MetricType_of :ATTR(:get<MetricType>);
my %Count_of :ATTR(:get<Count>);

__PACKAGE__->_factory(
    [ qw(        MetricType
        Count

    ) ],
    {
        'MetricType' => \%MetricType_of,
        'Count' => \%Count_of,
    },
    {
        'MetricType' => 'SUSHI::SUSHITypes::MetricType',
        'Count' => 'SOAP::WSDL::XSD::Typelib::Builtin::nonNegativeInteger',
    },
    {

        'MetricType' => 'MetricType',
        'Count' => 'Count',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

SUSHI::SUSHITypes::PerformanceCounter

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
PerformanceCounter from the namespace http://www.niso.org/schemas/counter.

UNUSED




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * MetricType


=item * Count




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::PerformanceCounter
   MetricType => $some_value, # MetricType
   Count =>  $some_value, # nonNegativeInteger
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

