package SUSHI::SUSHITypes::ReportRequest;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.niso.org/schemas/sushi/counter' };

our $XML_ATTRIBUTE_CLASS = 'SUSHI::SUSHITypes::ReportRequest::_ReportRequest::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Requestor_of :ATTR(:get<Requestor>);
my %CustomerReference_of :ATTR(:get<CustomerReference>);
my %ReportDefinition_of :ATTR(:get<ReportDefinition>);

__PACKAGE__->_factory(
    [ qw(        
        Requestor
        CustomerReference
        ReportDefinition
    ) ],
    {
        'Requestor' => \%Requestor_of,
        'CustomerReference' => \%CustomerReference_of,
        'ReportDefinition' => \%ReportDefinition_of,
    },
    {
        'Requestor' => 'SUSHI::SUSHITypes::Requestor',
        'CustomerReference' => 'SUSHI::SUSHITypes::CustomerReference',
        'ReportDefinition' => 'SUSHI::SUSHITypes::ReportDefinition',
    },
    {

        'Requestor' => 'Requestor',
        'CustomerReference' => 'CustomerReference',
        'ReportDefinition' => 'ReportDefinition',
    }
);



sub __my_serialize {
    # we work on @_ for performance.
    $_[1] ||= {};                                   # $option_ref

    @{ $_[1]->{ xmlns_stack } } = ( 'http://www.niso.org/schemas/sushi/counter', 'http://www.niso.org/schemas/sushi' );

    # get content first (pass by reference to avoid copying)
    my $content_ref = $_[0]->_serialize($_[1]);     # option_ref

    pop @{ $_[1]->{ xmlns_stack } };

    # do we have a empty element ?
    return $_[0]->start_tag({ %{ $_[1] }, empty => 1 })
        if not length ${ $content_ref };

    return join q{}, $_[0]->start_tag($_[1]), ${ $content_ref }, $_[0]->end_tag();
}

*{SUSHI::SUSHITypes::ReportRequest::serialize} = \&__my_serialize;

} # end BLOCK




package SUSHI::SUSHITypes::ReportRequest::_ReportRequest::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %Created_of :ATTR(:get<Created>);
my %ID_of :ATTR(:get<ID>);

__PACKAGE__->_factory(
    [ qw(
        Created
        ID
    ) ],
    {
        Created => \%Created_of,
        ID => \%ID_of,
    },
    {
        Created => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        ID => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

SUSHI::SUSHITypes::ReportRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ReportRequest from the namespace http://www.niso.org/schemas/sushi.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Requestor


=item * CustomerReference


=item * ReportDefinition




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::ReportRequest
   Requestor =>  { # SUSHI::SUSHITypes::Requestor
     ID =>  $some_value, # string
     Name =>  $some_value, # string
     Email =>  $some_value, # string
   },
   CustomerReference =>  { # SUSHI::SUSHITypes::CustomerReference
     ID =>  $some_value, # string
     Name =>  $some_value, # string
   },
   ReportDefinition =>  { # SUSHI::SUSHITypes::ReportDefinition
     Filters =>  {
       UsageDateRange =>  { # SUSHI::SUSHITypes::Range
         Begin =>  $some_value, # date
         End =>  $some_value, # date
       },
     },
   },
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class SUSHI::SUSHITypes::ReportRequest::_ReportRequest::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * Created

 Date/time the request was created



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::dateTime|SOAP::WSDL::XSD::Typelib::Builtin::dateTime>.

=item * ID

 Identifier may be provided by client application for internal use/diagnostics.



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::string|SOAP::WSDL::XSD::Typelib::Builtin::string>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

