package SUSHI::SUSHITypes::ReportResponse;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.niso.org/schemas/sushi' };

our $XML_ATTRIBUTE_CLASS = 'SUSHI::SUSHITypes::ReportResponse::_ReportResponse::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Exception_of :ATTR(:get<Exception>);
my %Requestor_of :ATTR(:get<Requestor>);
my %CustomerReference_of :ATTR(:get<CustomerReference>);
my %ReportDefinition_of :ATTR(:get<ReportDefinition>);

__PACKAGE__->_factory(
    [ qw(        Exception
        Requestor
        CustomerReference
        ReportDefinition

    ) ],
    {
        'Exception' => \%Exception_of,
        'Requestor' => \%Requestor_of,
        'CustomerReference' => \%CustomerReference_of,
        'ReportDefinition' => \%ReportDefinition_of,
    },
    {
        'Exception' => 'SUSHI::SUSHITypes::Exception',
        'Requestor' => 'SUSHI::SUSHITypes::Requestor',
        'CustomerReference' => 'SUSHI::SUSHITypes::CustomerReference',
        'ReportDefinition' => 'SUSHI::SUSHITypes::ReportDefinition',
    },
    {

        'Exception' => 'Exception',
        'Requestor' => 'Requestor',
        'CustomerReference' => 'CustomerReference',
        'ReportDefinition' => 'ReportDefinition',
    }
);

} # end BLOCK




package SUSHI::SUSHITypes::ReportResponse::_ReportResponse::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %Created_of :ATTR(:get<Created>);
my %ID_of :ATTR(:get<ID>);

__PACKAGE__->_factory(
    [ qw(
        Created
        ID
    ) ],
    {

        Created => \%Created_of,

        ID => \%ID_of,
    },
    {
        Created => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        ID => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

SUSHI::SUSHITypes::ReportResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ReportResponse from the namespace http://www.niso.org/schemas/sushi.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Exception


=item * Requestor


=item * CustomerReference


=item * ReportDefinition




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::ReportResponse
   Exception =>  { # SUSHI::SUSHITypes::Exception
     Number =>  $some_value, # int
     Severity => $some_value, # ExceptionSeverity
     Message =>  $some_value, # string
     HelpUrl =>  $some_value, # anyURI
     Data =>  $some_value, # anyType
   },
   Requestor =>  { # SUSHI::SUSHITypes::Requestor
     ID =>  $some_value, # string
     Name =>  $some_value, # string
     Email =>  $some_value, # string
   },
   CustomerReference =>  { # SUSHI::SUSHITypes::CustomerReference
     ID =>  $some_value, # string
     Name =>  $some_value, # string
   },
   ReportDefinition =>  { # SUSHI::SUSHITypes::ReportDefinition
     Filters =>  {
       UsageDateRange =>  { # SUSHI::SUSHITypes::Range
         Begin =>  $some_value, # date
         End =>  $some_value, # date
       },
     },
   },
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class SUSHI::SUSHITypes::ReportResponse::_ReportResponse::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * Created

 Date/time the response was created



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::dateTime|SOAP::WSDL::XSD::Typelib::Builtin::dateTime>.

=item * ID

 If the ReportRequest had an ID, return in this attribute.



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::string|SOAP::WSDL::XSD::Typelib::Builtin::string>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

