package SUSHI::SUSHITypes::Reports;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://www.niso.org/schemas/counter' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Report_of :ATTR(:get<Report>);

__PACKAGE__->_factory(
    [ qw(        Report

    ) ],
    {
        'Report' => \%Report_of,
    },
    {
        'Report' => 'SUSHI::SUSHITypes::Report',
    },
    {

        'Report' => 'Report',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

SUSHI::SUSHITypes::Reports

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Reports from the namespace http://www.niso.org/schemas/counter.

Can contain many Reports.




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Report




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::Reports
   Report =>  { # SUSHI::SUSHITypes::Report
     Vendor => 
 # No documentation generated for complexContent / extension yet
,
     Customer =>  {
       ReportItems =>  { # SUSHI::SUSHITypes::ReportItem
         ItemIdentifier =>  { # SUSHI::SUSHITypes::Identifier
           Type => $some_value, # IdentifierType
           Value =>  $some_value, # string
         },
         ItemPlatform =>  $some_value, # string
         ItemPublisher =>  $some_value, # string
         ItemName =>  $some_value, # string
         ItemDataType => $some_value, # DataType
         ItemPerformance =>  { # SUSHI::SUSHITypes::Metric
           Period =>  { # SUSHI::SUSHITypes::DateRange
             Begin =>  $some_value, # date
             End =>  $some_value, # date
           },
           Category => $some_value, # Category
           Instance =>  { # SUSHI::SUSHITypes::PerformanceCounter
             MetricType => $some_value, # MetricType
             Count =>  $some_value, # nonNegativeInteger
           },
         },
       },
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

