package SUSHI::SUSHITypes::ReportDefinition;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.niso.org/schemas/sushi' };

our $XML_ATTRIBUTE_CLASS = 'SUSHI::SUSHITypes::ReportDefinition::_ReportDefinition::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Filters_of :ATTR(:get<Filters>);

__PACKAGE__->_factory(
    [ qw(        Filters

    ) ],
    {
        'Filters' => \%Filters_of,
    },
    {

        'Filters' => 'SUSHI::SUSHITypes::ReportDefinition::_Filters',
    },
    {

        'Filters' => 'Filters',
    }
);

} # end BLOCK




package SUSHI::SUSHITypes::ReportDefinition::_Filters;
use strict;
use warnings;
{
our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

sub get_xmlns { 'http://www.niso.org/schemas/sushi' };

__PACKAGE__->_set_element_form_qualified(1);

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %UsageDateRange_of :ATTR(:get<UsageDateRange>);

__PACKAGE__->_factory(
    [ qw(        
        UsageDateRange
    ) ],
    {
        'UsageDateRange' => \%UsageDateRange_of,
    },
    {
        'UsageDateRange' => 'SUSHI::SUSHITypes::Range',
    },
    {
        'UsageDateRange' => 'UsageDateRange',
    }
);

} # end BLOCK






}



package SUSHI::SUSHITypes::ReportDefinition::_ReportDefinition::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %Name_of :ATTR(:get<Name>);
my %Release_of :ATTR(:get<Release>);

__PACKAGE__->_factory(
    [ qw(
        Name
        Release
    ) ],
    {

        Name => \%Name_of,

        Release => \%Release_of,
    },
    {
        Name => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        Release => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

SUSHI::SUSHITypes::ReportDefinition

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ReportDefinition from the namespace http://www.niso.org/schemas/sushi.

Input arguments for the report.




=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Filters




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::ReportDefinition
   Filters =>  {
     UsageDateRange =>  { # SUSHI::SUSHITypes::Range
       Begin =>  $some_value, # date
       End =>  $some_value, # date
     },
   },
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class SUSHI::SUSHITypes::ReportDefinition::_ReportDefinition::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * Name

 Report name. See http://www.niso.org/workrooms/sushi/reports for a list of registered report names and releases.



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::string|SOAP::WSDL::XSD::Typelib::Builtin::string>.

=item * Release

 The release number corresponding to the COUNTER Code of Practice when the current definition of the report was introduced.



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::string|SOAP::WSDL::XSD::Typelib::Builtin::string>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

