package SUSHI::SUSHITypes::Requestor;
use strict;
use warnings;

__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.niso.org/schemas/sushi' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();


{ # BLOCK to scope variables

my %ID_of :ATTR(:get<ID>);
my %Name_of :ATTR(:get<Name>);
my %Email_of :ATTR(:get<Email>);

__PACKAGE__->_factory(
    [ qw(
        ID
        Name
        Email
    ) ],
    {
        'ID' => \%ID_of,
        'Name' => \%Name_of,
        'Email' => \%Email_of,
    },
    {
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Email' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ID' => 'ID',
        'Name' => 'Name',
        'Email' => 'Email',
    }
);

} # end BLOCK

1;


=pod

=head1 NAME

SUSHI::SUSHITypes::Requestor

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Requestor from the namespace http://www.niso.org/schemas/sushi.

Service consumer(client). Identifies the customer or 3rd party acting on behalf of customer.

=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ID


=item * Name


=item * Email




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::Requestor
   ID =>  $some_value, # string
   Name =>  $some_value, # string
   Email =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

