package SUSHI::SUSHIInterfaces::SushiService::SushiServicePort;
use strict;
use warnings;
use Class::Std::Fast::Storable;
use Scalar::Util qw(blessed);
use base qw(SOAP::WSDL::Client::Base);

# only load if it hasn't been loaded before
require SUSHI::SUSHITypemaps::SushiService
    if not SUSHI::SUSHITypemaps::SushiService->can('get_class');

sub START {
    $_[0]->set_proxy('') if not $_[2]->{proxy};
    $_[0]->set_class_resolver('SUSHI::SUSHITypemaps::SushiService')
        if not $_[2]->{class_resolver};

    $_[0]->set_prefix($_[2]->{use_prefix}) if exists $_[2]->{use_prefix};
}

sub GetReport {
    my ($self, $body, $header) = @_;
    die "GetReport must be called as object method (\$self is <$self>)" if not blessed($self);
    return $self->SUPER::call({
        operation => 'GetReport',
        soap_action => 'SushiService:GetReportIn',
        style => 'document',
        body => {
           'use'            => 'literal',
            namespace       => 'http://schemas.xmlsoap.org/wsdl/soap/',
            encodingStyle   => '',
            parts           =>  [qw( SUSHI::SUSHIElements::ReportRequest )],
        },
        header => {
            
        },
        headerfault => {
            
        },
    }, $body, $header);
}




1;



__END__

=pod

=head1 NAME

SUSHI::SUSHIInterfaces::SushiService::SushiServicePort - SOAP Interface for the SushiService Web Service

=head1 SYNOPSIS

 use SUSHI::SUSHIInterfaces::SushiService::SushiServicePort;
 my $interface = SUSHI::SUSHIInterfaces::SushiService::SushiServicePort->new();

 my $response;
 $response = $interface->GetReport();



=head1 DESCRIPTION

SOAP Interface for the SushiService web service
located at .

=head1 SERVICE SushiService



=head2 Port SushiServicePort



=head1 METHODS

=head2 General methods

=head3 new

Constructor.

All arguments are forwarded to L<SOAP::WSDL::Client|SOAP::WSDL::Client>.

=head2 SOAP Service methods

Method synopsis is displayed with hash refs as parameters.

The commented class names in the method's parameters denote that objects
of the corresponding class can be passed instead of the marked hash ref.

You may pass any combination of objects, hash and list refs to these
methods, as long as you meet the structure.

List items (i.e. multiple occurences) are not displayed in the synopsis.
You may generally pass a list ref of hash refs (or objects) instead of a hash
ref - this may result in invalid XML if used improperly, though. Note that
SOAP::WSDL always expects list references at maximum depth position.

XML attributes are not displayed in this synopsis and cannot be set using
hash refs. See the respective class' documentation for additional information.



=head3 GetReport



Returns a L<SUSHI::SUSHIElements::ReportResponse|SUSHI::SUSHIElements::ReportResponse> object.

 $response = $interface->GetReport( { # SUSHI::SUSHITypes::ReportRequest
    Requestor =>  { # SUSHI::SUSHITypes::Requestor
      ID =>  $some_value, # string
      Name =>  $some_value, # string
      Email =>  $some_value, # string
    },
    CustomerReference =>  { # SUSHI::SUSHITypes::CustomerReference
      ID =>  $some_value, # string
      Name =>  $some_value, # string
    },
    ReportDefinition =>  { # SUSHI::SUSHITypes::ReportDefinition
      Filters =>  {
        UsageDateRange =>  { # SUSHI::SUSHITypes::Range
          Begin =>  $some_value, # date
          End =>  $some_value, # date
        },
      },
    },
  },,
 );



=head1 AUTHOR

Generated by SOAP::WSDL on Mon May 31 16:08:10 2010

=cut
