package SUSHI::SUSHIElements::ReportRequest;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.niso.org/schemas/sushi/counter' }

__PACKAGE__->__set_name('ReportRequest');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SUSHI::SUSHITypes::ReportRequest
);

}

1;


=pod

=head1 NAME

SUSHI::SUSHIElements::ReportRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
ReportRequest from the namespace http://www.niso.org/schemas/sushi/counter.

Request from SUSHI::SUSHI Client requesting a COUNTER report.





=head1 METHODS

=head2 new

 my $element = SUSHI::SUSHIElements::ReportRequest->new($data);

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::ReportRequest
   Requestor =>  { # SUSHI::SUSHITypes::Requestor
     ID =>  $some_value, # string
     Name =>  $some_value, # string
     Email =>  $some_value, # string
   },
   CustomerReference =>  { # SUSHI::SUSHITypes::CustomerReference
     ID =>  $some_value, # string
     Name =>  $some_value, # string
   },
   ReportDefinition =>  { # SUSHI::SUSHITypes::ReportDefinition
     Filters =>  {
       UsageDateRange =>  { # SUSHI::SUSHITypes::Range
         Begin =>  $some_value, # date
         End =>  $some_value, # date
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

