
package SUSHI::SUSHIElements::ReportResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.niso.org/schemas/sushi/counter' }

__PACKAGE__->__set_name('ReportResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SUSHI::SUSHITypes::CounterReportResponse
);

}

1;


=pod

=head1 NAME

SUSHI::SUSHIElements::ReportResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
ReportResponse from the namespace http://www.niso.org/schemas/sushi/counter.

The report response for COUNTER reports (CounterReportResponse).





=head1 METHODS

=head2 new

 my $element = SUSHI::SUSHIElements::ReportResponse->new($data);

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::CounterReportResponse
   Report =>  { # SUSHI::SUSHITypes::Reports
     Report =>  { # SUSHI::SUSHITypes::Report
       Vendor =>  { # SUSHI::SUSHITypes::Vendor
       },
       Customer =>  {
         ReportItems =>  { # SUSHI::SUSHITypes::ReportItem
           ItemIdentifier =>  { # SUSHI::SUSHITypes::Identifier
             Type => $some_value, # IdentifierType
             Value =>  $some_value, # string
           },
           ItemPlatform =>  $some_value, # string
           ItemPublisher =>  $some_value, # string
           ItemName =>  $some_value, # string
           ItemDataType => $some_value, # DataType
           ItemPerformance =>  { # SUSHI::SUSHITypes::Metric
             Period =>  { # SUSHI::SUSHITypes::DateRange
               Begin =>  $some_value, # date
               End =>  $some_value, # date
             },
             Category => $some_value, # Category
             Instance =>  { # SUSHI::SUSHITypes::PerformanceCounter
               MetricType => $some_value, # MetricType
               Count =>  $some_value, # nonNegativeInteger
             },
           },
         },
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

