
package SUSHI::SUSHIElements::Reports;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.niso.org/schemas/counter' }

__PACKAGE__->__set_name('Reports');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SUSHI::SUSHITypes::Reports
);

}

1;


=pod

=head1 NAME

SUSHI::SUSHIElements::Reports

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
Reports from the namespace http://www.niso.org/schemas/counter.

COUNTER Reports. The "Reports" (plural) is not actually used in SUSHI::SUSHI. The COUNTER_SUSHI::SUSHI schema includes is own "Report" element which is of type c:Reports (see below). Which means the the SUSHI::SUSHI ReportResponse will include usually just one "Report" (singular) element





=head1 METHODS

=head2 new

 my $element = SUSHI::SUSHIElements::Reports->new($data);

Constructor. The following data structure may be passed to new():

 { # SUSHI::SUSHITypes::Reports
   Report =>  { # SUSHI::SUSHITypes::Report
     Vendor =>  { # SUSHI::SUSHITypes::Vendor
     },
     Customer =>  {
       ReportItems =>  { # SUSHI::SUSHITypes::ReportItem
         ItemIdentifier =>  { # SUSHI::SUSHITypes::Identifier
           Type => $some_value, # IdentifierType
           Value =>  $some_value, # string
         },
         ItemPlatform =>  $some_value, # string
         ItemPublisher =>  $some_value, # string
         ItemName =>  $some_value, # string
         ItemDataType => $some_value, # DataType
         ItemPerformance =>  { # SUSHI::SUSHITypes::Metric
           Period =>  { # SUSHI::SUSHITypes::DateRange
             Begin =>  $some_value, # date
             End =>  $some_value, # date
           },
           Category => $some_value, # Category
           Instance =>  { # SUSHI::SUSHITypes::PerformanceCounter
             MetricType => $some_value, # MetricType
             Count =>  $some_value, # nonNegativeInteger
           },
         },
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

